version: '3.8'

services:
  vue-frontend:
    container_name: simple-wallet-frontend
    build: .
    ports:
      - '5173:80'
    environment:
      VUE_APP_API_BASE_URL: 'http://localhost:8000/api'
      VITE_API_BASE_URL: 'http://127.0.0.1:8000/api/v1/'
      VITE_MONNIFY_API_KEY: MK_TEST_J66Q1EGXCM
      VITE_MONNIFY_CONTRACT_CODE: 3452430117
